apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: devtest-ingress-eks
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/group.name: "alb-group"
    external-dns.alpha.kubernetes.io/hostname: devtest.tl.scntl.com
spec:
  ingressClassName: alb
  rules:
  - host: devtest.tl.scntl.com
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.appName }}
            port:
              number: {{ .Values.containerPort.http }}

      - path: /
        pathType: Exact
        backend:
          service:
            name: {{ .Values.appName }}
            port:
              number: {{ .Values.containerPort.http }}